version: "3.9"

services:
  backend:
    build:
      context: ../../app
    container_name: devops_backend
    ports:
      - "5000:5000"
    environment:
      APP_ENV: docker
      APP_VERSION: v1-docker
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: devopsdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: devops_db
    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
